AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Azure Blob to S3 Migration Tool
    
    A tool that migrates/synchronizes Azure Blob storage to Amazon S3.

##################################################################
#
#  Globals
#
##################################################################
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

   

Resources:
##################################################################
#
#  IAM Roles
#
##################################################################
    BlobCopyLambdaRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument: 
                Version: "2012-10-17"
                Statement: 
                    - 
                        Effect: "Allow"
                        Principal: 
                            Service: 
                                - "lambda.amazonaws.com"
                        Action: 
                            - "sts:AssumeRole"
            Path: "/"
            Policies: 
                -
                    PolicyName: "AzureBlobToS3Policy"
                    PolicyDocument: 
                        Version: 2012-10-17
                        Statement:
                          - Effect: Allow
                            Action:
                                - ssm:GetParameters
                                - ssm:GetParameter
                                - ssm:GetParameterHistory
                            Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/AzureBlobToS3/*'
                          - Effect: Allow
                            Action:
                                - xray:PutTraceSegments
                                - xray:PutTelemetryRecords
                                - xray:GetSamplingRules
                                - xray:GetSamplingTargets
                                - xray:GetSamplingStatisticSummaries
                            Resource: '*'
                          - Effect: Allow
                            Action:
                                - lambda:InvokeFunction
                                - lambda:InvokeAsync
                            Resource: '*'
                          - Effect: Allow
                            Action:
                                - s3:GetObject
                                - s3:ListBucket
                                - s3:ListObjects
                            Resource: 
                                - !Join
                                    -   ''
                                    -   - !GetAtt AzureSyncBucket.Arn
                                        - '/*'
                                - !GetAtt AzureSyncBucket.Arn
                          - Effect: Allow
                            Action:
                                - logs:*
                            Resource: '*'
                          - Effect: Allow
                            Action:
                                - sqs:SendMessage
                                - sqs:ReceiveMessage
                                - sqs:DeleteMessage
                                - sqs:ChangeMessageVisibility
                                - sqs:GetQueueUrl
                                - sqs:GetQueueAttributes
                            Resource:
                                - !GetAtt BlobCopyQueue.Arn

##################################################################
#
#  SQS Queues
#
##################################################################

    BlobCopyQueue:
        Type: AWS::SQS::Queue
        Properties:
            QueueName: BlobCopyQueue
            VisibilityTimeout: 900

##################################################################
#
#  S3 Buckets
#
##################################################################

    AzureSyncBucket:
        Type: AWS::S3::Bucket

##################################################################
#
#  Lambda Functions
#
##################################################################
    AzureBlobToS3:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ./artifacts/AzureBlobToS3.zip
            Runtime: dotnetcore2.1
            MemorySize: 1024
            Timeout: 90
            Role: !GetAtt BlobCopyLambdaRole.Arn
            Handler: AzureBlobToS3::AzureBlobToS3.Function::FunctionHandler
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    ComprehensiveCheck: false
                    QueueName: !Ref BlobCopyQueue
            Tracing: Active  # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html

    CopyBlobToS3:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: ./artifacts/CopyAzureBlobToS3.zip
            Runtime: dotnetcore2.1
            MemorySize: 1024
            Timeout: 900
            Role: !GetAtt BlobCopyLambdaRole.Arn
            Handler: CopyAzureBlobToS3::CopyAzureBlobToS3.Function::FunctionHandler
            Tracing: Active
            Events:
                CopyBlobEvent:
                    Type: SQS
                    Properties:
                        Queue: !GetAtt BlobCopyQueue.Arn
                        BatchSize: 5

##################################################################
#
#  SSM Parameter Store parameters
#
##################################################################
    AzureStorageConnectionSSMParameter:
        Type: AWS::SSM::Parameter
        Properties:
            Name: '/AzureBlobToS3/StorageConnection'
            Description: 'The Azure connection string to use to conenct to the storage blobs.'
            Type: String
            Value: '*'
    
    AzureContainerNamesSSMParameter:
        Type: AWS::SSM::Parameter
        Properties:
            Name: '/AzureBlobToS3/StorageContainerNames'
            Description: 'The Azure container names to search in.'
            Type: StringList
            Value: '*'
    
    S3SyncBucketNameParameter:
        Type: AWS::SSM::Parameter
        Properties:
            Name: '/AzureBlobToS3/S3SyncBucketName'
            Description: 'The name of the S3 bucket to copy data to.'
            Type: String
            Value: !Ref AzureSyncBucket

    S3SyncRegionParameter:
        Type: AWS::SSM::Parameter
        Properties:
            Name: '/AzureBlobToS3/S3SyncRegion'
            Description: 'The region of the S3 bucket to copy data to.'
            Type: String
            Value: 'ap-southeast-1'